# .github/workflows/build-plugin.yml

name: Build O-MVLL Plugin on macOS

# Controls when the action will run.
on:
  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

  # Triggers the workflow on push events
  push:

jobs:
  build:
    # The type of runner that the job will run on
    runs-on: macos-latest

    steps:
      # Step 1: Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - name: Checkout Code
        uses: actions/checkout@v4

      # Step 2: Install Homebrew for x86_64 under Rosetta 2
      - name: Install x86_64 Homebrew
        run: |
          NONINTERACTIVE=1 arch -x86_64 /bin/bash -c "$(curl -fsSL https://raw.githubusercontent.com/Homebrew/install/HEAD/install.sh)"

      # Step 3: Install all necessary x86_64 build dependencies using the x86_64 Homebrew
      - name: Install x86_64 Dependencies via Homebrew
        run: /usr/local/bin/brew install cmake ninja spdlog pybind11 llvm@15

      - name: Set up Python 3.10.7 for x86_64
        uses: actions/setup-python@v4
        with:
          python-version: '3.10.7'
          architecture: 'x64'

      # Step 4: Create a build directory and configure the project with CMake for x86_64
      - name: Configure CMake for x86_64
        run: |
          mkdir -p src/build
          cd src/build
          /usr/local/bin/cmake .. -G Ninja -DOMVLL_TARGET_ARCHS=x86_64 -DLLVM_DIR=$(/usr/local/bin/brew --prefix llvm@15)/lib/cmake/llvm

      # Step 5: Compile the plugin for x86_64
      - name: Build the Plugin for x86_64
        run: /usr/local/bin/cmake --build src/build

      # Step 6: Upload the final .dylib file as a downloadable artifact
      - name: Upload Artifact
        uses: actions/upload-artifact@v4
        with:
          name: omvll-plugin-x86_64
          path: src/build/libOMVLL.dylib